//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F.FINANCIAMIENTO.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUENTES_FINANCIAMIENTO
    {
        public short FUENTE { get; set; }
        public short GRUPO_FUENTE { get; set; }
        public short SUB_GRUPO_FUENTE { get; set; }
        public string DESC_FUENTE { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual GRUPOS_FUENTES_FIN GRUPOS_FUENTES_FIN { get; set; }
    }
}
