//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F.FINANCIAMIENTO.DA
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class EntitiesFF : DbContext
    {
        public EntitiesFF()
            : base("name=EntitiesFF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FUENTES_FINANCIAMIENTO> FUENTES_FINANCIAMIENTO { get; set; }
        public DbSet<GRUPOS_FUENTES_FIN> GRUPOS_FUENTES_FIN { get; set; }
    }
}
