//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F.FINANCIAMIENTO.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOS_FUENTES_FIN
    {
        public GRUPOS_FUENTES_FIN()
        {
            this.FUENTES_FINANCIAMIENTO = new HashSet<FUENTES_FINANCIAMIENTO>();
        }
    
        public short GRUPO_FUENTE { get; set; }
        public string DESC_GRUPO_FUENTE { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<FUENTES_FINANCIAMIENTO> FUENTES_FINANCIAMIENTO { get; set; }
    }
}
